// CodeInspector.js - Right-side panel that shows the generated JS from the current graph

window.NodesCanvas = window.NodesCanvas || {};

window.NodesCanvas.CodeInspector = {
    _panel: null,
    _codeEl: null,
    _isOpen: false,

    init() {
        this._panel = document.getElementById('code-inspector');
        this._codeEl = document.getElementById('code-inspector-content');
        document.getElementById('code-inspector-close')?.addEventListener('click', () => this.close());
        document.getElementById('code-inspector-download')?.addEventListener('click', () => this.download());
        document.getElementById('code-inspector-refresh')?.addEventListener('click', () => this.refresh());
    },

    open() {
        this._isOpen = true;
        this._panel.classList.remove('ci-hidden');
        document.querySelector('.settings-container').classList.add('pushed');
        this.refresh();
    },

    close() {
        this._isOpen = false;
        this._panel.classList.add('ci-hidden');
        document.querySelector('.settings-container').classList.remove('pushed');
    },

    toggle() {
        this._isOpen ? this.close() : this.open();
    },

    refresh() {
        const code = this._generateCode();
        this._render(code);
    },

    _generateCode() {
        const engine = window.NodesCanvas.GraphEngine;
        if (!engine) return '// GraphEngine not available';

        const { nodes, conns } = engine._buildGraph();
        const order = engine._topoSort(nodes, conns);

        const lines = [];
        lines.push(`// ============================================================`);
        lines.push(`// Generated by Nodes Canvas Studio`);
        lines.push(`// ${new Date().toLocaleString()}`);
        lines.push(`// ============================================================`);
        lines.push('');

        // 1. Data Sources (Manual Data)
        const dataNodes = Object.values(nodes).filter(n => n.type === 'manual-data');
        const dataVars = {}; // nodeId -> uniqueVariableName
        const usedDataNames = new Set();

        if (dataNodes.length) {
            lines.push('// --- Data Sources ---');
            dataNodes.forEach(n => {
                let baseName = engine._toVar(n.label || 'data');
                // Ensure uniqueness
                if (usedDataNames.has(baseName)) {
                    let counter = 1;
                    while (usedDataNames.has(`${baseName}_${counter}`)) counter++;
                    baseName = `${baseName}_${counter}`;
                }
                usedDataNames.add(baseName);
                dataVars[n.id] = baseName;

                const keyword = n.isConstant ? 'const' : 'let';
                lines.push(`${keyword} ${baseName} = ${JSON.stringify(n.value)};`);
            });
            lines.push('');
        }

        // 2. Function Deduplication logic
        const fns = Object.values(nodes).filter(n => n.type === 'function' && n.code);
        const uniqueFns = new Map(); // code -> uniqueFnName

        if (fns.length) {
            lines.push('// --- Node Functions ---');
            fns.forEach(fn => {
                // Remove comments for a cleaner key check (or just use raw code)
                const codeKey = fn.code.trim();
                if (!uniqueFns.has(codeKey)) {
                    const fnName = `node_${engine._toVar(fn.label)}`;
                    uniqueFns.set(codeKey, fnName);
                    lines.push(`// Node Type: ${fn.label}`);
                    lines.push(fn.code.replace(/\bfunction execute\b/, `function ${fnName}`));
                    lines.push('');
                }
            });
        }

        // 3. Execution chain
        lines.push('// --- Execution ---');
        const portToVar = {}; // portId -> variableExpression

        // Map data node outputs
        dataNodes.forEach(n => {
            portToVar[n.outPortId] = dataVars[n.id];
        });

        const usedNodeNames = new Set();

        order.forEach(nodeId => {
            const node = nodes[nodeId];
            if (node.type === 'manual-data' || !node.code) {
                // Special case for call-data which is a "passthrough" from a manual-data var
                if (node.type === 'call-data') {
                    const sourceVar = dataVars[node.sourceId] || 'undefined';
                    let nodeBase = engine._toVar(node.label);
                    if (usedNodeNames.has(nodeBase)) {
                        let c = 1;
                        while (usedNodeNames.has(`${nodeBase}_${c}`)) c++;
                        nodeBase = `${nodeBase}_${c}`;
                    }
                    usedNodeNames.add(nodeBase);
                    const resultVar = `out_${nodeBase}`;
                    lines.push(`const ${resultVar} = ${sourceVar}; // Linked from ${node.label}`);

                    node.outputPorts.forEach((p) => {
                        portToVar[p] = resultVar;
                    });
                }
                return;
            }

            const args = {};
            conns.forEach(conn => {
                if (conn.targetNodeId !== nodeId) return;
                const idx = node.inputPorts.indexOf(conn.targetPortId);
                const label = engine._toVar(idx >= 0 ? (node.inputLabels?.[idx] || conn.targetPortId) : conn.targetPortId);
                args[label] = portToVar[conn.sourcePortId] ?? 'undefined';
            });

            const fnName = uniqueFns.get(node.code.trim());

            // Unique result variable for this specific node instance
            let nodeBase = engine._toVar(node.label);
            if (usedNodeNames.has(nodeBase)) {
                let c = 1;
                while (usedNodeNames.has(`${nodeBase}_${c}`)) c++;
                nodeBase = `${nodeBase}_${c}`;
            }
            usedNodeNames.add(nodeBase);
            const resultVar = `out_${nodeBase}`;

            const argStr = Object.entries(args).map(([k, v]) => `${k}: ${v}`).join(', ');
            lines.push(`const ${resultVar} = ${fnName}({ ${argStr} });`);
            lines.push(`console.log('[${node.label}]', ${resultVar});`);

            node.outputPorts.forEach((p, i) => {
                const outLabel = engine._toVar(node.outputLabels?.[i] || p);
                portToVar[p] = `${resultVar}.${outLabel}`;
            });
        });

        if (Object.keys(portToVar).length > dataNodes.length) {
            lines.push('');
            lines.push('// --- Final ---');
            Object.entries(portToVar).forEach(([portId, varExpr]) => {
                // Only show final results (those not used as input downstream, or just show all for simplicity)
                // For now, let's just list all named out_ vars
                if (varExpr.startsWith('out_')) {
                    lines.push(`// Result: ${varExpr}`);
                }
            });
        }

        return lines.join('\n');
    },

    _render(code) {
        if (!this._codeEl) return;

        // Simple JS syntax highlighting via regex
        const escaped = code
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');

        const highlighted = escaped
            // Comments
            .replace(/(\/\/[^\n]*)/g, '<span class="ci-comment">$1</span>')
            // Strings
            .replace(/(&quot;[^&]*&quot;|'[^']*'|`[^`]*`)/g, '<span class="ci-string">$1</span>')
            // Keywords
            .replace(/\b(const|let|var|function|return|if|else|for|while|new|this)\b/g, '<span class="ci-keyword">$1</span>')
            // Numbers
            .replace(/\b(\d+\.?\d*)\b/g, '<span class="ci-number">$1</span>');

        this._codeEl.innerHTML = highlighted;
    },

    async download() {
        const code = this._generateCode();
        try {
            if (window.showSaveFilePicker) {
                const handle = await window.showSaveFilePicker({
                    suggestedName: 'nodes_canvas_export.js',
                    types: [{
                        description: 'JavaScript File',
                        accept: { 'application/javascript': ['.js'] },
                    }],
                });
                const writable = await handle.createWritable();
                await writable.write(code);
                await writable.close();
            } else {
                const blob = new Blob([code], { type: 'text/javascript' });
                const url = URL.createObjectURL(blob);
                const a = Object.assign(document.createElement('a'), { href: url, download: 'nodes_canvas_export.js' });
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
            }
        } catch (err) {
            if (err.name !== 'AbortError') console.error('Save failed', err);
        }
    },
};

document.addEventListener('DOMContentLoaded', () => {
    window.NodesCanvas.CodeInspector.init();
});
