// CodeInspector.js - Right-side panel that shows the generated JS from the current graph
// Refactored to match current BaseNode/Node classes

window.NodesCanvas = window.NodesCanvas || {};

window.NodesCanvas.CodeInspector = {
    _panel: null,
    _codeEl: null,
    _isOpen: false,

    init() {
        this._panel = document.getElementById('code-inspector');
        this._codeEl = document.getElementById('code-inspector-content');
        document.getElementById('code-inspector-close')?.addEventListener('click', () => this.close());
        document.getElementById('code-inspector-download')?.addEventListener('click', () => this.download());
        document.getElementById('code-inspector-refresh')?.addEventListener('click', () => this.refresh());
    },

    open() {
        this._isOpen = true;
        this._panel.classList.remove('ci-hidden');
        document.querySelector('.settings-container').classList.add('pushed');
        this.refresh();
    },

    close() {
        this._isOpen = false;
        this._panel.classList.add('ci-hidden');
        document.querySelector('.settings-container').classList.remove('pushed');
    },

    toggle() {
        this._isOpen ? this.close() : this.open();
    },

    refresh() {
        const code = this._generateCode();
        this._render(code);
    },

    _generateCode() {
        const engine = window.NodesCanvas.GraphEngine;
        if (!engine) return '// GraphEngine not available';

        const { nodes, connections } = engine._buildGraph();
        const order = engine._executionOrder; // Already sorted in _buildGraph

        const lines = [];
        lines.push(`// ============================================================`);
        lines.push(`// Generated by Nodes Canvas Studio`);
        lines.push(`// ${new Date().toLocaleString()}`);
        lines.push(`// ============================================================`);
        lines.push('');

        // 1. Identification and Variable Naming
        const dataVars = {}; // nodeId -> uniqueVariableName
        const nodeOutputVars = {}; // nodeId -> resultVarName
        const portToVar = {}; // socketId -> fullVariableExpression (e.g., out_myAdd.Result)

        const usedNames = new Set();
        const getUniqueName = (base) => {
            let name = engine._toVar(base);
            if (usedNames.has(name)) {
                let c = 1;
                while (usedNames.has(`${name}_${c}`)) c++;
                name = `${name}_${c}`;
            }
            usedNames.add(name);
            return name;
        };

        // 2. Data Sources (Manual Data & Sliders)
        const dataNodes = Object.values(nodes).filter(n => n instanceof window.NodesCanvas.ManualDataNode || n instanceof window.NodesCanvas.SliderNode);
        if (dataNodes.length) {
            lines.push('// --- Data Sources ---');
            dataNodes.forEach(n => {
                const varName = getUniqueName(n.title || (n instanceof window.NodesCanvas.SliderNode ? 'slider' : 'data'));
                dataVars[n.id] = varName;

                if (n instanceof window.NodesCanvas.SliderNode) {
                    lines.push(`const ${varName} = ${n.value}; // Slider`);
                } else {
                    const keyword = n.isConstant ? 'const' : 'let';
                    lines.push(`${keyword} ${varName} = ${JSON.stringify(n.value)}; // Panel`);
                }
                // Map output port: ManualData and Slider use {id}_out
                portToVar[`${n.id}_out`] = varName;
            });
            lines.push('');
        }

        // 3. Logic Functions Deduplication
        const logicNodes = Object.values(nodes).filter(n => (n instanceof window.NodesCanvas.Node || n instanceof window.NodesCanvas.ExpressionNode) && n.code);
        const uniqueLogicFns = new Map(); // code -> fnName

        if (logicNodes.length) {
            lines.push('// --- Logic Functions ---');
            logicNodes.forEach(n => {
                if (n instanceof window.NodesCanvas.ExpressionNode) return; // Special inline handling

                const codeKey = n.code.trim();
                if (!uniqueLogicFns.has(codeKey)) {
                    const fnName = getUniqueName(n.title || 'function');
                    uniqueLogicFns.set(codeKey, fnName);
                    lines.push(`function ${fnName}({ ${n.inputs.map(i => i.id).join(', ')} }) {`);
                    lines.push(n.code.replace(/^return\s+/, '  return ')); // Simple indent
                    lines.push(`}`);
                    lines.push('');
                }
            });
        }

        // 4. Execution Chain
        lines.push('// --- Process ---');
        order.forEach(nodeId => {
            const node = nodes[nodeId];
            if (dataNodes.includes(node)) return; // Already handled

            // Viewer node: just a comment of the input
            if (node instanceof window.NodesCanvas.ViewerNode) {
                const incoming = connections.find(c => c.toNodeId === nodeId);
                const val = incoming ? (portToVar[incoming.fromPortId] || 'undefined') : 'undefined';
                lines.push(`// Viewer [${node.id}]: Displaying ${val}`);
                return;
            }

            // Call Data (Linked from a data source)
            if (node instanceof window.NodesCanvas.CallDataNode) {
                const sourceVar = dataVars[node.sourceId] || 'undefined';
                const resultVar = getUniqueName(`out_${node.label || 'linked'}`);
                lines.push(`const ${resultVar} = ${sourceVar}; // Call Data from ${node.label}`);
                // Call data nodes effectively pass through to all their outputs (usually 1)
                if (node.outputs) {
                    node.outputs.forEach(p => portToVar[p.id] = resultVar);
                }
                return;
            }

            // Logic nodes
            if (!node.code) return;

            const resVar = getUniqueName(`out_${node.title || 'node'}`);
            nodeOutputVars[nodeId] = resVar;

            // Gather inputs
            const inputArgs = {};
            node.inputs.forEach(inp => {
                const conn = connections.find(c => c.toNodeId === nodeId && c.toPortId === inp.id);
                inputArgs[inp.id] = conn ? (portToVar[conn.fromPortId] || 'undefined') : 'undefined';
            });
            const argStr = Object.entries(inputArgs).map(([k, v]) => `${k}: ${v}`).join(', ');

            if (node instanceof window.NodesCanvas.ExpressionNode) {
                // Inline expression
                lines.push(`const ${resVar} = { Result: (${node.code}) }; // Expression`);
            } else {
                // Call deduplicated function
                const fnName = uniqueLogicFns.get(node.code.trim());
                lines.push(`const ${resVar} = ${fnName}({ ${argStr} });`);
            }

            // Map outputs
            if (node.outputs) {
                node.outputs.forEach(outPort => {
                    portToVar[outPort.id] = `${resVar}.${engine._toVar(outPort.id)}`;
                });
            }
        });

        lines.push('');
        lines.push('// --- Final Output ---');
        // Filter out variables that are just properties (like out_Add.Result)
        // Show the top-level results for each branch
        const finalResults = [...new Set(Object.values(portToVar).map(v => v.split('.')[0]))];
        finalResults.forEach(rv => {
            if (rv.startsWith('out_')) {
                lines.push(`console.log("Result node:", ${rv});`);
            }
        });

        return lines.join('\n');
    },

    _render(code) {
        if (!this._codeEl) return;

        const escaped = code
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');

        const highlighted = escaped
            .replace(/(\/\/[^\n]*)/g, '<span class="ci-comment">$1</span>')
            .replace(/(&quot;[^&]*&quot;|'[^']*'|`[^`]*`)/g, '<span class="ci-string">$1</span>')
            .replace(/\b(const|let|var|function|return|if|else|for|while|new|this)\b/g, '<span class="ci-keyword">$1</span>')
            .replace(/\b(\d+\.?\d*)\b/g, '<span class="ci-number">$1</span>');

        this._codeEl.innerHTML = highlighted;
    },

    async download() {
        const code = this._generateCode();
        try {
            if (window.showSaveFilePicker) {
                const handle = await window.showSaveFilePicker({
                    suggestedName: 'nodes_canvas_export.js',
                    types: [{
                        description: 'JavaScript File',
                        accept: { 'application/javascript': ['.js'] },
                    }],
                });
                const writable = await handle.createWritable();
                await writable.write(code);
                await writable.close();
            } else {
                const blob = new Blob([code], { type: 'text/javascript' });
                const url = URL.createObjectURL(blob);
                const a = Object.assign(document.createElement('a'), { href: url, download: 'nodes_canvas_export.js' });
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
            }
        } catch (err) {
            if (err.name !== 'AbortError') console.error('Save failed', err);
        }
    },
};

document.addEventListener('DOMContentLoaded', () => {
    window.NodesCanvas.CodeInspector.init();
});
